# Task 3 (Tuple Operations)
Nigerian_states = input("Dear User, Kindly enter 5 Nigerian states\nNote: ensure you put space before entering another\nNow proceed: ")
Splitted = Nigerian_states.split(" ")
# print(Splitted)
tupple1 = tuple(Splitted)
# print(tupple1)
# print(type(tupple1))
print(tupple1[::4])
print("Lagos" in tupple1)
print(len(tupple1))