# Task 2 (Tuple and Input)
print("Dear user, Kindly input the names of your 5 best friends..")
first = input("Input 1st friend name: ")
second = input("Input 2nd friend name: ")
third = input("Input 3rd friend name: ")
fourth = input("Input 4th friend name: ")
fifth = input("Input 5th friend name: ")
tuple_friends = (first, second, third, fourth, fifth)
print(tuple_friends[::-1])