# Task 5 (Modify Tuple Indirectly)
shopping_list = input("Dear user, kindly input three items for your shopping list.\nEnsure you put space before next item.\nNow input: ")
tuple_shopping_list = (shopping_list)
list_conversion = tuple_shopping_list.split()
add_shopping_list1 = input("Kindly add two more items\n enter 1st item: ")
add_shopping_list2 = input("enter 2nd item: ")
list_conversion.append(add_shopping_list1)
list_conversion.append(add_shopping_list2)
print(list_conversion)
tuple_conversion = tuple(list_conversion)
join = " | ".join(tuple_conversion)
print(join)